### ISSUE TITLE
HEY

### ISSUE THREAD

**Issue by darkdarcool** [TheQuackyDuck/TheQuackyDuck#5]
`Slowly becoming a java dev`

HEY

Did you copy my `Slowly becoming a nodejs dev`??! 

## >:(

(jk i don't care)

**Comment by TheQuackyDuck** [comment]
haha yes ~~ur very smart~~

**Comment by darkdarcool** [comment]
Big brain, smort, 1000 iq

**Comment by TheQuackyDuck** [comment]
xP
